server:
  port: 8080

spring:
  boot:
    admin:
      client:
        instance:
          name: Client Server
          service-url: "http://localhost:8080"
        url: "http://localhost:8090"
        auto-registration: true
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, metrics, logfile, env
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ./logs/application.log
