server:
  port: 8080

spring:
  # spring boot admin client 관련 설정
  boot:
    admin:
      client:
        instance:
          # Client display name
          name: Client Server
          # 현재 돌아가고 있는 서버, 즉 spring boot admin client의 주소
          service-url: "http://localhost:8080"
        # spring boot admin server의 주소
        url: "http://localhost:8090"
        # true로 설정하면 애플리케이션을 등록하는 주기적인 작업이 애플리케이션이 준비된 후 자동으로 예약됨
        auto-registration: true
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, metrics, logfile, env
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ./logs/application.log
